AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Parameters:
  SourceBucket:
    Type: String
    Default: howwhofeelinvideopackage
  ExcelKey:
    Type: String
    Default: MakeAppointmentChatBot.xlsx
Resources:
 # custom resource to create Lex component from excel
  LexBuilderCustomReseourcesFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: main.lambda_handler
      Runtime: python3.6
      MemorySize: 512
      Timeout: 300
      Tracing: Active
      Policies:
        - AWSXrayWriteOnlyAccess
        - AWSLambdaExecute
        - AWSLambdaBasicExecutionRole
        - AmazonS3ReadOnlyAccess
        - AmazonLexFullAccess
      CodeUri:
        Bucket: !Ref SourceBucket
        Key: lex_builder_function.zip
      Environment:
        Variables:
          SourceBucket: !Ref SourceBucket
          ExcelKey: !Ref ExcelKey

  LexBuilderCustomReseources:
    Type: Custom::LexBuilder
    DependsOn:
      - LexBuilderCustomReseourcesFunction
    Version: 1.0
    Properties:
      ServiceToken: !GetAtt LexBuilderCustomReseourcesFunction.Arn
      StackName:
        Ref: AWS::StackName
      SourceBucket: !Ref SourceBucket
      ExcelKey: !Ref ExcelKey



