AWSTemplateFormatVersion: 2010-09-09
Description: Upload Excel xlsx to S3 and trigger Excel Lex Bot
Parameters:
  ExcelBucketName:
    Default: excellexbot4
    Type: String
  SourceBucket:
    Default: howwhofeelinvideopackage
    Type: String
Resources:
  Bucket:
    Properties:
      BucketName:
        Ref: ExcelBucketName
    Type: AWS::S3::Bucket
  ExcelLexBotS3TriggerFunction:
    Properties:
      CodeUri:
        Bucket:
          Ref: SourceBucket
        Key: lex_builder_function.zip
      Description: Create Lex Chat Bot when upload xlsx file.
      Events:
        XlsxUpload:
          Properties:
            Bucket:
              Ref: Bucket
            Events: s3:ObjectCreated:*
            Filter:
              S3Key:
                Rules:
                - Name: suffix
                  Value: .xlsx
          Type: S3
      FunctionName: ExcelLexBotS3Trigger
      Handler: s3_trigger_handler.lambda_handler
      MemorySize: 512
      Policies:
      - AWSXrayWriteOnlyAccess
      - AWSLambdaExecute
      - AWSLambdaBasicExecutionRole
      - AmazonLexFullAccess
      - AmazonSNSFullAccess
      - Statement:
        - Action:
          - cloudformation:CreateStack
          - cloudformation:DescribeChangeSet
          - cloudformation:CreateChangeSet
          - cloudformation:DeleteStack
          - cloudformation:ExecuteChangeSet
          - dynamodb:DescribeTable
          - dynamodb:PutItem
          - dynamodb:UpdateTable
          - lambda:InvokeFunction
          - lambda:ListFunctions
          - lambda:GetFunction
          - cloudwatch:DescribeAlarms
          - cloudwatch:PutMetricAlarm
          - cloudwatch:DeleteAlarms
          Effect: Allow
          Resource: '*'
        Version: 2012-10-17
      Runtime: python3.6
      Timeout: 300
      Tracing: Active
    Type: AWS::Serverless::Function
Transform: AWS::Serverless-2016-10-31
